name: platform-spigot
version: '1.0.0'
main: com.zetaplugins.netwatchz.spigot.NetwatchZSpigot
api-version: '1.19'
load: STARTUP
description: Anti VPN, Geoblocking and IP tracking plugin 
website: zetaplugins.com
