name: NetwatchZ
version: '1.0.0'
main: com.zetaplugins.netwatchz.paper.NetwatchZPaper
api-version: '1.17'
load: STARTUP
description: Anti VPN, Geoblocking and IP tracking plugin 
website: zetaplugins.com

commands:
  ipinfo:
    description: Get information about a player's IP address
    permission: netwatchz.ipinfo

permissions:
  netwatchz.ipinfo:
    description: Allows the player to use the /ipinfo command
    default: op
  netwatchz.bypass:
    description: Allows the player to bypass all checks
    default: op
  netwatchz.admin.debug:
    description: Allows the player to generate debug reports
    default: op